restart-watcher-deps:
    FROM golang:1.18-alpine3.15
    RUN apk add build-base
    WORKDIR /builder
    COPY go.mod .
    COPY go.sum .
    RUN go mod download
    SAVE ARTIFACT go.mod AS LOCAL go.mod
    SAVE ARTIFACT go.sum AS LOCAL go.sum

build-restart-watcher:
    FROM +restart-watcher-deps
    COPY --dir . .
    RUN CGO_ENABLED=0 go build -o /bin/restart-watcher ./main.go
    SAVE ARTIFACT /bin/restart-watcher AS LOCAL ./artifacts/restart-watcher
